# Generated by Django 4.0.1 on 2022-01-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "tg_username",
                    models.CharField(max_length=200, verbose_name="Telegram username"),
                ),
                (
                    "discord_username",
                    models.CharField(max_length=200, verbose_name="Discord username"),
                ),
            ],
        ),
    ]
