# Generated by Django 4.0.1 on 2022-01-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(max_length=200, verbose_name="Time slot"),
                ),
            ],
        ),
    ]
