# Generated by Django 4.0.1 on 2022-01-28 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_student_in_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="counter",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="Students in Team",
            ),
        ),
    ]
