# Generated by Django 4.0.1 on 2022-01-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0013_alter_team_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="level",
            field=models.CharField(
                default="rara", max_length=200, verbose_name="Level"
            ),
            preserve_default=False,
        ),
    ]
