# Generated by Django 4.0.1 on 2022-01-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_remove_team_counter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pm",
            name="time_slots",
        ),
        migrations.RemoveField(
            model_name="student",
            name="in_team",
        ),
        migrations.RemoveField(
            model_name="student",
            name="time_slot",
        ),
        migrations.RemoveField(
            model_name="team",
            name="time_slot",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="time_slot",
        ),
        migrations.AddField(
            model_name="pm",
            name="timeslot",
            field=models.ManyToManyField(
                max_length=200,
                related_name="PMs",
                to="teams.TimeSlot",
                verbose_name="Timeslot",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="timeslot",
            field=models.ManyToManyField(
                blank=True,
                related_name="Students",
                to="teams.TimeSlot",
                verbose_name="Student timeslot",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="timeslot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Teams",
                to="teams.timeslot",
                verbose_name="Team timeslot",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="timeslot",
            field=models.CharField(default=[], max_length=200, verbose_name="Timeslot"),
            preserve_default=False,
        ),
    ]
