# Generated by Django 4.0.1 on 2022-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_remove_pm_time_slots_remove_student_in_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_team',
            field=models.BooleanField(default=False, verbose_name='Student already in team'),
        ),
    ]
