# Generated by Django 4.0.1 on 2022-01-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_creator', '0005_pm_time_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='team_creator.timeslot', verbose_name='Team time slot'),
        ),
    ]
