# Generated by Django 4.0.1 on 2022-01-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_creator', '0007_student_team_student_time_slot_alter_team_pm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Students', to='team_creator.student', verbose_name='Team students'),
        ),
    ]
