# Generated by Django 4.0.1 on 2022-01-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_creator', '0010_alter_team_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='in_team',
            field=models.BooleanField(default=False, verbose_name='Studetn already in team'),
        ),
    ]
