# Generated by Django 4.0.1 on 2022-01-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_creator', '0014_team_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='counter',
        ),
    ]
